language: java
before_install:
  - pip install --user pip --upgrade pip
  - pip install --user cython --upgrade Cython
  - pip install --user pyjnius --upgrade pyjnius 
install: true
jdk:
  - oraclejdk8
after_script:
  python simple_searcher_test.py
